import type { Finding, Severity } from "../types.js";
import type { AggregatedResult } from "./aggregator.js";
import type { ProxyInfo } from "../types.js";

const SEVERITY_EMOJI: Record<Severity, string> = {
  CRITICAL: "🔴 CRITICAL",
  HIGH: "🟠 HIGH",
  MEDIUM: "🟡 MEDIUM",
  LOW: "🟢 LOW",
};

const VERDICT_HEADER: Record<string, string> = {
  SAFE: "# ✅ SAFE — Upgrade Appears Safe",
  UNSAFE: "# 🚨 UNSAFE — Do Not Upgrade",
  REVIEW_REQUIRED: "# ⚠️ REVIEW REQUIRED — Manual Review Needed",
  INCOMPLETE: "# ❓ INCOMPLETE — Analysis Could Not Complete",
};

export function generateMarkdownReport(
  aggregated: AggregatedResult,
  proxyInfo: ProxyInfo | undefined,
  metadata: {
    proxyAddress: string;
    newImplementationPath: string;
    oldImplementationPath: string;
    timestamp: string;
  },
): string {
  const lines: string[] = [];

  // Header
  lines.push(VERDICT_HEADER[aggregated.verdict] ?? `# ${aggregated.verdict}`);
  lines.push("");
  lines.push(`**Analyzed:** ${metadata.timestamp}`);
  lines.push(`**Proxy:** \`${metadata.proxyAddress}\``);
  if (proxyInfo) {
    lines.push(`**Proxy Type:** ${proxyInfo.type === "uups" ? "UUPS" : "Transparent"}`);
    lines.push(`**Current Implementation:** \`${proxyInfo.implementationAddress}\``);
    if (proxyInfo.adminAddress) {
      lines.push(`**Admin:** \`${proxyInfo.adminAddress}\``);
    }
  }
  lines.push(`**Old Implementation:** \`${metadata.oldImplementationPath}\``);
  lines.push(`**New Implementation:** \`${metadata.newImplementationPath}\``);
  lines.push("");

  // Severity summary
  lines.push("## Severity Summary");
  lines.push("");
  const counts: Record<Severity, number> = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
  for (const f of aggregated.findings) counts[f.severity]++;
  lines.push("| Severity | Count |");
  lines.push("| -------- | ----- |");
  for (const sev of ["CRITICAL", "HIGH", "MEDIUM", "LOW"] as Severity[]) {
    lines.push(`| ${SEVERITY_EMOJI[sev]} | ${counts[sev]} |`);
  }
  lines.push("");

  // Analyzer status
  lines.push("## Analyzer Status");
  lines.push("");
  lines.push("| Analyzer | Status |");
  lines.push("| -------- | ------ |");
  for (const [name, status] of Object.entries(aggregated.analyzerStatus)) {
    const icon = status === "completed" ? "✅" : status === "skipped" ? "⏭" : "❌";
    lines.push(`| ${name} | ${icon} ${status} |`);
  }
  lines.push("");

  // Critical and High findings — full detail
  const criticalAndHigh = aggregated.findings.filter(
    (f) => f.severity === "CRITICAL" || f.severity === "HIGH",
  );
  if (criticalAndHigh.length > 0) {
    lines.push("## Critical & High Findings");
    lines.push("");
    for (const finding of criticalAndHigh) {
      lines.push(
        `### ${SEVERITY_EMOJI[finding.severity]} [${finding.code}] ${finding.title}`,
      );
      lines.push("");
      lines.push(finding.description);
      lines.push("");
      if (finding.location) {
        const loc = finding.location;
        const parts = [
          loc.contract ? `Contract: \`${loc.contract}\`` : null,
          loc.function ? `Function: \`${loc.function}\`` : null,
          loc.slot !== undefined ? `Slot: ${loc.slot}` : null,
          loc.offset !== undefined ? `Offset: ${loc.offset}` : null,
          loc.file ? `File: \`${loc.file}:${loc.line ?? ""}\`` : null,
        ].filter(Boolean);
        if (parts.length > 0) {
          lines.push(`**Location:** ${parts.join(" | ")}`);
          lines.push("");
        }
      }
      if (Object.keys(finding.details).length > 0) {
        lines.push("**Details:**");
        lines.push("```json");
        lines.push(JSON.stringify(finding.details, null, 2));
        lines.push("```");
        lines.push("");
      }
      lines.push(`**Remediation:** ${finding.remediation}`);
      lines.push("");
      lines.push("---");
      lines.push("");
    }
  }

  // Medium and Low findings — summary table
  const mediumAndLow = aggregated.findings.filter(
    (f) => f.severity === "MEDIUM" || f.severity === "LOW",
  );
  if (mediumAndLow.length > 0) {
    lines.push("## Medium & Low Findings");
    lines.push("");
    lines.push("| Code | Severity | Title |");
    lines.push("| ---- | -------- | ----- |");
    for (const f of mediumAndLow) {
      lines.push(`| ${f.code} | ${SEVERITY_EMOJI[f.severity]} | ${f.title} |`);
    }
    lines.push("");
  }

  if (aggregated.findings.length === 0) {
    lines.push("## No findings.");
    lines.push("");
    lines.push("The upgrade appears safe. All analyzers completed with no issues.");
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by decipher-solidity-upgradoor v0*");

  return lines.join("\n");
}
